Setup:
  # Token for the account you want it to login too
  Token: Token
Settings:
  StatusType: PLAYING #PLAYING: WATCHING: LISTENING: STREAMING:
  StatusMessage: Placeholer
Commands:
  # This only needs to be enabled for the first run to register the commands with discord as it means starting takes longer to avoid rate limiting
  SetupCommands: false
  # Wether not the commands are registered to only one guild (Recomend to leave it on false for global commands (will take up to an hour to register))
  JustGuildCommands: true
  # If JustGuildCommands is enabled the ID of the guild to register them too
  GuildID: ""